Dice Roller 0.1/Pages/CC1.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Xml.Linq;
using System.Net;

namespace Dice_Roller_0._1.Pages
{

    public class CC1Model : PageModel
    {

        public void OnGet()
        {

            Cookie charCookie = new Cookie("charCookie", "_str:12,_dex:15,_con:14,_int:10,_wis:9,_cha:11,_name:Bob,_race:elf,_class:fighter,_maxHP:12,_currHP:8,_bg:soldier,_al:LG,_size:medium");
            //Cookie goober = new Cookie("newCookie", Request.Cookies["charCookie"]);
            Response.Cookies.Append("charCookie", charCookie.Value);
            ViewData["charBob"] = Request.Cookies["charCookie"];

            //Console.WriteLine(Request.Cookies["charCookie"]);

            ViewData["IsPost"] = false;
        }

        public void OnPost()
        {
            ViewData["IsPost"] = true;
        }

        //race(human), class(bard), ...abilities(1,2,3,4,...)
    }
}

Dice Roller 0.1/Pages/CC2.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net;

namespace Dice_Roller_0._1.Pages
{
    public class CC2Model : PageModel
    {
        public void OnGet()
        {
            Character testChar = makeCharacter(ViewData["CC1Char"]!.ToString()!);
            //Console.WriteLine(testChar.getBg());
            //Console.WriteLine("Made a(n) " + testChar.getRace() + " " + testChar.getClass());
            string encryptedChar = "_str:" + testChar.getStr() + ",_dex:" + testChar.getDex() + ",_con:" + testChar.getCon() +
                ",_int:" + testChar.getInt() + ",_wis:" + testChar.getWis() + ",_cha:" + testChar.getCha() +
                ",_name:" + testChar.getName() + ",_race:" + testChar.getRace() + ",_class:" + testChar.getClass() +
                ",_maxHP:" + testChar.getMaxHP() + ",_currHP:" + testChar.getCurrHP() + ",_bg:" + testChar.getBg() +
                ",_al:" + testChar.getAl() + ",_size:" + testChar.getSize();
            ViewData["CC2Display"] = encryptedChar;
        }

        public void OnPostTEST()
        {

            
            Character testChar = makeCharacter(ViewData["CC1Char"]!.ToString()!);
            //Console.WriteLine(testChar.getBg());
            //Console.WriteLine("Made a(n) " + testChar.getRace() + " " + testChar.getClass());
            string encryptedChar = "_str:" + testChar.getStr() + ",_dex:" + testChar.getDex() + ",_con:" + testChar.getCon() + 
                ",_int:" + testChar.getInt() + ",_wis:" + testChar.getWis() + ",_cha:" + testChar.getCha() + 
                ",_name:" + testChar.getName() + ",_race:" + testChar.getRace() + ",_class:" + testChar.getClass() + 
                ",_maxHP:" + testChar.getMaxHP() + ",_currHP:" + testChar.getCurrHP() + ",_bg:" + testChar.getBg() + 
                ",_al:" + testChar.getAl() + ",_size:" + testChar.getSize();
            //ViewData["testChar"] = encryptedChar;
            
        }

        public Character makeCharacter(string input)
        {
            //creates a character using only a encrypted string
            //creates all of the variables that will be used to make the character
            int[] stats = new int[6];
            string name = "";
            string race = "";
            string _class = "";
            int maxHP = 0;
            int currHP = 0;
            string bg = "";
            string al = "";

            //splits the inputed encrypted string into an array of strings
            char[] delimitersChars = { '_', ':', ',' };

            string[] splitInfo = input.Split(delimitersChars);

            //sorts out all of the empty strings in splitInfo

            string[] sortedInfo = new string[28];
            int index = 0;
            for (int i = 0; i < splitInfo.Length; i++)
            {
                if (splitInfo[i] != "")
                {
                    sortedInfo[index] = splitInfo[i];
                    index++;
                }
            }

            stats[0] = Convert.ToInt32(sortedInfo[1]);
            stats[1] = Convert.ToInt32(sortedInfo[3]);
            stats[2] = Convert.ToInt32(sortedInfo[5]);
            stats[3] = Convert.ToInt32(sortedInfo[7]);
            stats[4] = Convert.ToInt32(sortedInfo[9]);
            stats[5] = Convert.ToInt32(sortedInfo[11]);

            name = sortedInfo[Array.IndexOf(sortedInfo,"name") + 1];
            race = sortedInfo[Array.IndexOf(sortedInfo, "race") + 1];
            _class = sortedInfo[Array.IndexOf(sortedInfo, "class") + 1];
            maxHP = Convert.ToInt32(sortedInfo[Array.IndexOf(sortedInfo, "maxHP") + 1]);
            currHP = Convert.ToInt32(sortedInfo[Array.IndexOf(sortedInfo, "currHP") + 1]);
            bg = sortedInfo[Array.IndexOf(sortedInfo, "bg") + 1];
            al = sortedInfo[Array.IndexOf(sortedInfo, "al") + 1];

            Character test = new Character(stats, name, race, _class, maxHP, currHP, bg, al);
            return test;
        }

       



        //this is an old method used to test how to retrieve data from an encrypted string
        /*
        public int[] retrieve()
        {
            char[] delimitersChars = { '_', ':', ',' };
            //string info = "_str:12,_dex:15,_con:14,_int:10,_wis:9,_cha:11,_name:Bob,_race:elf,_class:fighter,_maxHP:12,_currHP:8,_bg:soldier,_al:LG,_size:medium";
            string info = Convert.ToString(ViewData["charBob"])!;
            int str = 0;
            int dex = 0;
            int con = 0;
            int intel = 0;
            int wis = 0;
            int cha = 0;

            //splits the decrypted string but doesn't sort out the empty strings
            string[] splitInfo = info.Split(delimitersChars);

            //Console.WriteLine(splitInfo.Length);
            //foreach(string x in splitInfo)
            //{
            //    Console.WriteLine(x);
            //}

            //sorts out all of the empty strings in splitInfo

            string[] sortedInfo = new string[28];
            int index = 0;
            for (int i = 0; i<splitInfo.Length; i++)
            {
                if (splitInfo[i] != "")
                {
                    sortedInfo[index] = splitInfo[i];
                    index++;
                }
            }

            //str = Convert.ToInt32(info.Substring(info.IndexOf("_str:") + 5, info.IndexOf(",_dex:") - 5));

            //decrypts the string
            str = Convert.ToInt32(sortedInfo[1]);
            dex = Convert.ToInt32(sortedInfo[3]);
            con = Convert.ToInt32(sortedInfo[5]);
            intel = Convert.ToInt32(sortedInfo[7]);
            wis = Convert.ToInt32(sortedInfo[9]);
            cha = Convert.ToInt32(sortedInfo[11]);

            //tests to see if the strenght is correctly retreived
            //Console.WriteLine("Character strength: " +  str);
            return new int[] { str, dex, con, intel, wis, cha }; 
        }*/
        public void OnPostStoreStats()
        {
            string tempStorage = "_str:" + ViewData["strStat"] + ",_dex:" + ViewData["dexStat"] + ",_con:" + ViewData["conStat"] + ",_int:" + ViewData["intStat"] + ",_wis:" + ViewData["wisStat"] + ",_cha:" + ViewData["chaStat"];

            //Console.WriteLine(tempStorage + Request.Cookies["CC1Data"]);
            ViewData["CC2Char"] = tempStorage + Request.Cookies["CC1Data"];
        }

    }
}

Dice Roller 0.1/Pages/CCItems.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Dice_Roller_0._1.Pages
{
    public class CCItemsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Dice Roller 0.1/Pages/CC_BA.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Dice_Roller_0._1.Pages
{
    public class CC_BAModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Dice Roller 0.1/Pages/CC_CR.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Xml.Linq;
using System.Net;

namespace Dice_Roller_0._1.Pages
{

    public class CC1Model : PageModel
    {

        public void OnGet()
        {

            Cookie charCookie = new Cookie("charCookie", "_str:12,_dex:15,_con:14,_int:10,_wis:9,_cha:11,_name:Bob,_race:elf,_class:fighter,_maxHP:12,_currHP:8,_bg:soldier,_al:LG,_size:medium");
            //Cookie goober = new Cookie("newCookie", Request.Cookies["charCookie"]);
            Response.Cookies.Append("charCookie", charCookie.Value);
            ViewData["charBob"] = Request.Cookies["charCookie"];

            //Console.WriteLine(Request.Cookies["charCookie"]);

            ViewData["IsPost"] = false;
        }

        public void OnPost()
        {
            ViewData["IsPost"] = true;
        }

        //race(human), class(bard), ...abilities(1,2,3,4,...)
    }
}

Dice Roller 0.1/Pages/CC_sub1.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Dice_Roller_0._1.Pages
{
    public class CC_sub1Model : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Dice Roller 0.1/Pages/CharSheet.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Dice_Roller_0._1.Pages
{
    public class CharSheetModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Dice Roller 0.1/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Dice_Roller_0._1.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Dice Roller 0.1/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Dice_Roller_0._1.Pages
{
    public class IndexModel : PageModel
    {

        /* Comment out to match video
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }
        */

        /*
        * 1st - d4
        * 2nd - d6
        * 3rd - d8
        * 4th - d10
        * 5th - d10 (percentile)
        * 6th - d12
        * 7th - d20
        */

        //A default array for test buttons to use
        int[] dice = { 0, 0, 0, 0, 0, 0, 0 };
        int mod = 2;

        public void OnGet()
        {//Make a default array of 1 of each die
            int[] deArray = { 1, 1, 1, 1, 1, 1, 1 };
            Console.WriteLine(RollDice(deArray, 2));
            OnPostFourDrop();


        }

        public void MoreLessDice(int[] arr, int die,int add)
        {   //Adds or Subtracts a Die from the Array
            //add should be -1 or 1
            //find what die we want to add/subtract from array
            if (die == 4)
                arr[0] += add;
            else if (die == 6)
                arr[1] += add;
            else if (die == 8)
                arr[2] += add;
            else if (die == 10)
                arr[3] += add;
            else if (die == 100)
                arr[4] += add;
            else if (die == 12)
                arr[5] += add;
            else if (die == 20)
                arr[6] += add;
        }

        public int RollDice(int[] arr, int mod)
        {   //Rolls all Dice in Array and adds the Mod
            int sum = 0;
            Random roll = new Random();

            for(int i = 0; i < arr.Length;i++)
            {
               for(int j = 0; j < arr[i]; j++)
                {
                    //check which die type is being rolled
                    if (i == 0)
                    {//d4
                        sum += roll.Next(1, 5);
                        Console.WriteLine("Rolled d4");
                    }
                    else if (i == 1)
                    {//d6
                        sum += roll.Next(1, 7);
                        Console.WriteLine("Rolled d6");
                    }
                    else if (i == 2)
                    {//d8
                        sum += roll.Next(1, 9);
                        Console.WriteLine("Rolled d8");
                    }
                    else if (i == 3)
                    {//d10
                        sum += roll.Next(1, 11);
                        Console.WriteLine("Rolled d10");
                    }
                    else if (i == 4)
                    {//d10 (percentile)
                        sum += (roll.Next(1, 11) * 10);
                        Console.WriteLine("Rolled a d10 pct");
                    }
                    else if (i == 5)
                    {//d12
                        sum += roll.Next(1, 13);
                        Console.WriteLine("Rolled a d12");
                    }
                    else if (i == 6)
                    {//d20
                        sum += roll.Next(1, 21);
                        Console.WriteLine("Rolled a d20");
                    }                    
                }//roll loop
            }//position loop

            //add mod to sum
            sum += mod;
            //return rolled sum
            return sum;
        }

        public int fourDropLowest()
        {   //for creating stats
            int[] four = { 0, 0, 0, 0, 0, 0, 0 };

            //int logic
            int hold = 0;
            int low = 9999999;
            int sum = 0;

            for (int i = 0;i < 4;i++)
            {   //Roll single d6
                four[1] = 1;
                hold = RollDice(four, 0);

                //Add to total
                sum += hold;

                //Keep track of lowest value
                if (hold < low)
                    low = hold;
            }

            //Now drop lowest value
            sum -= low;

            //Return sum of dice rolls minus lowest value
            return sum;
        }

        public void OnPostButton()
        { 
            dice[0] = 1;
            dice[1] = 1;
            dice[2] = 1;
            dice[3] = 1;
            dice[4] = 1;
            dice[5] = 1;
            dice[6] = 1;
            Console.WriteLine(RollDice(dice, mod));  
        }

        public void OnPostTestClick()
        {
            Console.WriteLine("TEST");
        }
        public void OnPostFourDrop()
        {
            Console.WriteLine(fourDropLowest());
        }

    }
}

Dice Roller 0.1/Pages/MapMaker.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Dice_Roller_0._1.Pages
{
    public class MapMakerModel : PageModel
    {
        public void OnGet()
        {
            //Instantiate ViewData with default values
            //Not necessary, but a good programming habit
            //Needs to be instantiated here to be accessed in the .cshtml file without fails
            ViewData["isPost"] = "false";
        }

        public void OnPostMakeMap()
        {
                ViewData["isPost"] = "true";

        }

        public void OnPost()
        {

        }
    }
}

Dice Roller 0.1/Pages/CCItems.cshtml
@page
@model Dice_Roller_0._1.Pages.CCItemsModel
@{
    ViewData["Title"] = "Inventory";
}
<h1>Choose your Inventory by selecting an option from each drop down</h1>

<div class="text-center">
    <button class="backButton" onclick="window.location.href='/CC_sub1';">Back</button>
</div>

<script>
    /*--How many choices each class has to make for their inventory
        Barbarian - 2
        Bard - 3
        Cleric - 4
        Druid - 2
        Fighter - 4
        Monk - 2
        Paladin - 3
        Ranger - 3
        Rogue - 3
        Sorcerer - 3
        Warlock - 3
        Wizard - 3
    */

    
</script>

Dice Roller 0.1/Pages/CC_BA.cshtml
@page
@model Dice_Roller_0._1.Pages.CC_BAModel
@{
    ViewData["Title"] = "Character Creator";
}
<!--<script src="site.js"></script>
<button onclick="document.getElementById('demo').innerHTML = getCookie('selectClass')"></button>
<p id="demo"></p>
-->
<style>

    aside {
        position: fixed;
        border-radius: 20px;
        right: 150px;
        width: 27%;
        padding: 30px;
        margin: 10px;
        font-style: italic;
        background-color: lightgray;
        float: right;
        
    }

    #bgInfo {
        float: left;
        right: 0px;
        left: 150px;
    }

    table, tr, td {
        padding: 5px;
        margin: 5px;
        border-width: 2px;
        border-color: black;
        background-color: gray;
        color: black;
    }

    table {
        margin: auto;
    }
</style>

<form method="get" action="/CC_sub1">
    <div class="text-center">
    <h1 id="CCTitle">Character Creator</h1>
        <aside id="bgInfo">
            <h4>What is a Background?</h4>
            Your <strong>Background</strong> is what your life was like before your character started adventuring, this may be a job or the way you lived <br>
            They provide you with some known languages, skills you excell at, and starting gear - Don't worry too much about optimization, pick what you think fits the idea of your character!
        </aside>
        <aside>
            <h4>What is an Alignment?</h4>
            Your <strong>Alignment</strong> is your character's nature. It helps you figure out what your character would do in a situation <br>
            <strong>Good - Neutral - Evil</strong> is a range of morality. How much does your character value the common good, for example <br>
            <strong>Lawful - Neutral - Chaotic</strong> is a range of acting. Does your character follow a moral code, or do they do the first thing that comes to mind
        </aside>
        
    <h2>Background</h2>
    <!--Dropdown List to select from all backgrounds-->
    <label for="selectBackground">Choose a Background:</label>
    <select id="selectBackground" name="selectBackground" runat="server">
        <option value="">Choose a Background</option>
        <option value="acolyte">Acolyte</option>
        <option value="charlatan">Charlatan</option>
        <option value="criminal">Criminal</option>
        <option value="entertainer">Entertainer</option>
        <option value="folk-hero">Folk Hero</option>
        <option value="guild-artisan">Guild Artisan</option>
        <option value="hermit">Hermit</option>
        <option value="noble">Noble</option>
        <option value="outlander">Outlander</option>
        <option value="sage">Sage</option>
        <option value="sailor">Sailor</option>
        <option value="soldier">Soldier</option>
        <option value="urchin">Urchin</option>
    </select>
    <br />
    <h2>Alignment</h2>
    <!--Dropdown List to select from all alignments-->
    <label for="selectAlignment">Choose an Alignment:</label>
    <select id="selectAlignment" name="selectAlignment" runat="server">
        <option value="">Choose an Alignment</option>
        <option value="LG">Lawful Good</option>
        <option value="LN">Lawful Neutral</option>
        <option value="LE">Lawful Evil</option>
        <option value="NG">Neutral Good</option>
        <option value="TN">True Neutral</option>
        <option value="NE">Neutral Evil</option>
        <option value="CG">Chaotic Good</option>
        <option value="CN">Chaotic Neutral</option>
        <option value="CE">Chaotic Evil</option>
    </select>

    <h4>Click Submit then Continue</h4>
    <br />
        <!--Submit button that saves selected class in a variable-->
        <!--<input type="submit" value="Submit" class="submit" />-->
        <button type="submit" class="submitButton" onclick="storeInfo()">Submit</button>
    </div>
    </form>

    <div class="text-center">
    <button class="backButton" style="margin:auto;" onclick="window.location.href='/CC2';">Back</button>
    </div>

    <div>

</div>

<script>
    function storeInfo(){
        if (document.getElementById("selectBackground").value != "" || document.getElementById("selectBackground").value != null)
            localStorage.setItem("bg", document.getElementById("selectBackground").value);
        if (document.getElementById("selectAlignment").value != "" || document.getElementById("selectAlignment").value != null)
            localStorage.setItem("al", document.getElementById("selectAlignment").value);
    }
</script>

Dice Roller 0.1/Pages/CharSheet.cshtml
@page
@model Dice_Roller_0._1.Pages.CharSheetModel
@{
}
<h1><u>Character Sheet:</u></h1>
<h2>Character Info:</h2>
<p id="name"></p>
<p id="class"></p>
<p id="race"></p>
<p id="bg"></p>
<p id="al"></p>
<h2>Stats:</h2>
<p id="str"></p>
<p id="dex"></p>
<p id="con"></p>
<p id="int"></p>
<p id="wis"></p>
<p id="cha"></p>


<script>
    document.getElementById("name").innerHTML = "Name: " + localStorage.getItem("name");
    document.getElementById("class").innerHTML = "Class: " + localStorage.getItem("class");
    document.getElementById("race").innerHTML = "Race: " + localStorage.getItem("race");
    document.getElementById("bg").innerHTML = "Background: " + localStorage.getItem("bg");
    document.getElementById("al").innerHTML = "Alignment: " + localStorage.getItem("al");

    document.getElementById("str").innerHTML = "Strength: " + localStorage.getItem("str") + " Modifier: " + getMod(localStorage.getItem("str"));
    document.getElementById("dex").innerHTML = "Dexterity: " + localStorage.getItem("dex") + " Modifier: " + getMod(localStorage.getItem("dex"));
    document.getElementById("con").innerHTML = "Constitution: " + localStorage.getItem("con") + " Modifier: " + getMod(localStorage.getItem("con"));
    document.getElementById("int").innerHTML = "Intelligence: " + localStorage.getItem("int") + " Modifier: " + getMod(localStorage.getItem("int"));
    document.getElementById("wis").innerHTML = "Wisdom: " + localStorage.getItem("wis") + " Modifier: " + getMod(localStorage.getItem("wis"));
    document.getElementById("cha").innerHTML = "Charisma: " + localStorage.getItem("cha") + " Modifier: " + getMod(localStorage.getItem("cha"));

    function getMod(stat){
        return Math.floor((stat-10)/2);
    }
</script>

Dice Roller 0.1/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Realm Builder Home";

}

<script>
    if(sessionStorage.getItem("started") != "1")
        sessionStorage.setItem("started", "0");

</script>

<div class="text-center">
    <img src="/images/Realm Builder Logo.png" width="750">
    <p>
        <!--<button onclick="window.location.href='https://localhost:44331/CC1';">Create a Character</button>-->
        <button onclick="window.location.href='/CC_CR';">Create a Character</button>
    </p>
</div>

Dice Roller 0.1/Pages/MapMaker.cshtml
@page
@model Dice_Roller_0._1.Pages.MapMakerModel
@{
}
@{
    ViewData["Title"] = "Realm Builder";
}

<h1 id="CCTitle">Realm Designer</h1>

<div class="text-center">

    <form asp-page-handler="MakeMap" method="post">
        <label for="rowsBox"> Rows: </label>
        <label for="columnsBox"> Columns: </label> <br />
        <input type="text" pattern="^[0-9]*$" id="rowsBox " name="textRows" />
        <input type="text" pattern="^[0-9]*$" id="columnsBox " name="textColumns" />
        <!--<input type="text" id="rowsBox " name="textRows" />
        <input type="text" id="columnsBox " name="textColumns" /> <br />-->
        <button>Create Realm</button> <br />

    </form>



</div>
<br>
<br>

@{

    if (ViewData["isPost"]!.ToString() == "true")
    {   //Grab the Requested # of Rows and Columns
        //int R = Convert.ToInt32(Request.Form["textRows"]);
        //int C = Convert.ToInt32(Request.Form["textColumns"]);
        ViewData["rows"] = Convert.ToInt32(Request.Form["textRows"]);
        ViewData["columns"] = Convert.ToInt32(Request.Form["textColumns"]);

        //Create the Map Object, and the List we'll use to Display it
        Map original = new Map((int)ViewData["rows"]!, (int)ViewData["columns"]!);
        //List<Tile> og = new List<Tile>((int)ViewData["rows"]! * (int)ViewData["columns"]!);

        <img src="/images/GrassTile.png" alt="image here" style="display:block; max-width:100px; max-height:100px;" />





        /*
        //Creates a Table Using For Loops
        <table cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;">
            @{
                //Number of Rows
                for (int i = 0; i < (int)ViewData["rows"]!; i++)
                {
                    <tr>
                        @{
                            //Number of Columns
                            for (int j = 0; j < (int)ViewData["columns"]!; j++)
                            {
                                <td> <img src=@original.getTileString(i, j, "picture") alt="image here" style="display:block; max-width:100px; max-height:100px;" /></td>
                            }
                        }
                    </tr>
                }
            }
        </table> */
    }
}
<br />
<br />
<div class="text-center">
    <button class="backButton" onclick="window.location.href='/CC2';">Back</button><button class="continueButton" onclick="window.location.href='/Index';">Home</button>
</div>